import { useState } from 'react';
import type { AttachmentMetadataV2, StructuredWorkflowRequestV2, StructuredWorkflowResultV2 } from '@agent-dock/shared';
import { getBridge } from '../bridge.js';

export function WorkflowPanel({ sessionId }: { sessionId?: string }) {
  const [attachments, setAttachments] = useState<AttachmentMetadataV2[]>([]);
  const [schemaText, setSchemaText] = useState('{"type":"object","properties":{"answer":{"type":"string"}},"required":["answer"],"additionalProperties":false}');
  const [outputText, setOutputText] = useState('{"answer":""}');
  const [result, setResult] = useState<StructuredWorkflowResultV2>();
  const [error, setError] = useState<string>();
  async function selectFiles() { try { const selected = await getBridge().selectAndUploadAttachments(sessionId); setAttachments((current) => [...current, ...selected].slice(0, 20)); setError(undefined); } catch (failure) { setError(failure instanceof Error ? failure.message : 'Attachment upload failed'); } }
  async function validate() { try { const schema = JSON.parse(schemaText) as StructuredWorkflowRequestV2['schema']; const output = JSON.parse(outputText) as unknown; setResult(await getBridge().validateStructuredOutput({ schema, output })); setError(undefined); } catch (failure) { setError(failure instanceof Error ? failure.message : 'Structured output is invalid'); } }
  return <div>{error && <div className="banner banner--error" role="alert">{error}</div>}<button type="button" onClick={() => void selectFiles()}>Choose files</button><p className="form-hint">Files are selected by Electron and staged privately. The renderer never receives source paths or bytes. Staged files are not included in any run: no current adapter dispatches them to a provider session.</p><ul className="attachment-list" aria-label="Staged attachments">{attachments.map((item) => <li key={item.id}><strong>{item.fileName}</strong><span>{item.mimeType} · {(item.size / 1024).toFixed(1)} KiB · {item.referenced ? 'retained with session' : 'staged for 24h'}</span></li>)}</ul>{attachments.length === 0 && <p className="session-list__empty">No files staged yet.</p>}<details><summary>Structured output validation</summary><p className="form-hint">This checks a JSON payload you paste in against a schema. It does not constrain what a provider actually generates.</p><label>JSON Schema<textarea aria-label="JSON Schema" value={schemaText} onChange={(event) => setSchemaText(event.target.value)} rows={5} /></label><label>Output JSON<textarea aria-label="Output JSON" value={outputText} onChange={(event) => setOutputText(event.target.value)} rows={5} /></label><button type="button" onClick={() => void validate()}>Validate output</button>{result && <div className={`structured-result structured-result--${result.valid ? 'valid' : 'invalid'}`} role="status"><strong>{result.valid ? 'Schema-valid output' : 'Output is not schema-valid'}</strong>{result.errors.length > 0 && <table><thead><tr><th>Path</th><th>Error</th></tr></thead><tbody>{result.errors.map((item, index) => <tr key={`${item.path}:${index}`}><td><code>{item.path}</code></td><td>{item.message}</td></tr>)}</tbody></table>}<pre aria-label="Normalized output">{JSON.stringify(result.normalizedOutput, null, 2)}</pre></div>}</details></div>;
}
