import {
  DETERMINISTIC_GATE_IDS,
  modelTierRank,
  refineSpecV1Schema,
  reviewReportV1Schema,
  type CreateSessionV2Request,
  type DeterministicGateId,
  type DeterministicGateResultV1,
  type DiffScopeV1,
  type LlmReviewPassV1,
  type ModelTier,
  type ProviderId,
  type RefineSpecV1,
  type ReviewFindingV1,
  type ReviewReportV1,
  type VerifierPassV1,
} from '@agent-dock/shared';
import { runGitCommand, type PipenzoGitRunner } from './pipenzo-git.js';

/**
 * The Review phase (Pipenzo issue #181).
 *
 * This module exists to prove one property, and the property is an *ordering*:
 *
 * > Deterministic gates first. Only then an LLM review pass. Only then a separate adversarial
 * > verifier. Never reordered, never parallelized in a way that lets an LLM pass reach a verdict
 * > before the deterministic ones have.
 *
 * Three things make that structural rather than aspirational:
 *
 * 1. **`run()` is a straight line and cannot be entered halfway.** There is no public method that
 *    runs the reviewer, and none that runs the verifier. A caller cannot skip ahead because there
 *    is nothing to skip ahead to.
 * 2. **A deterministic failure returns before either LLM pass is constructed.** Not "is
 *    ignored" — returns. The report type then makes the inverse unrepresentable: a
 *    `ReviewReportV1` carrying a reviewer or verifier pass alongside a failed deterministic gate
 *    fails its own schema (`pipenzo-review-v1.ts`), so an ordering violation cannot be serialized
 *    even by a future caller assembling a report by hand.
 * 3. **The verifier's tier is asserted before it runs.** README states the same-or-higher rule as
 *    a hard rule, backed by cross-tier regression evidence (a weaker model reviewing a stronger
 *    one produced 3 fixes against 13 new bugs). A weaker verifier throws
 *    `ReviewGateError('verifier_tier_too_low')` rather than running and being ignored.
 *
 * ## Separation, which is a different property from ordering
 *
 * The reviewer sees the spec and the diff. It does not see the implementer's transcript, its
 * session id, or its worktree — README is explicit that same-session self-review measurably
 * underperforms a fresh session, and `buildReviewerPrompt()` takes a spec and a diff string and
 * nothing else, so there is no parameter through which a transcript could arrive.
 *
 * The spec-generated tests are subject to the same rule from the other direction: they are
 * generated by their own pass from the spec, never authored by the implementer whose work they
 * check. `SpecTestGeneratorPort` is that pass. When none is configured the `spec_tests` gate is
 * recorded as **skipped, with the reason** — never as passed. A machine check that did not run
 * must not be able to look like a machine check that succeeded, which is the whole premise of the
 * evidence block being worth reading.
 *
 * ## Explicitly NOT here, per the ticket
 *
 * Model-tier *routing* (routing classes to tiers is build step 4+), the risk classifier, and
 * retry ladders. The reviewer and verifier tiers and models are handed in by the caller as a
 * single hardcoded choice; this module only enforces the relationship between them.
 *
 * One README rule is deliberately **not** implemented, and is surfaced rather than silently
 * skipped: "a failing spec-generated test is not automatically the code's fault — it is
 * adjudicated once, by the verifier tier, into test-wrong or code-wrong." Implementing that here
 * would mean running the verifier to settle a deterministic gate, which inverts the very ordering
 * this ticket exists to establish. So a run whose *only* deterministic failure is `spec_tests`
 * returns the distinct outcome `awaiting_test_adjudication`, which says "a generated test failed
 * and nobody has ruled on whose fault that is" instead of blaming the code by default.
 */

export type ReviewGateErrorCode =
  | 'invalid_spec'
  | 'invalid_request'
  | 'verifier_tier_too_low'
  | 'diff_unavailable'
  | 'reviewer_failed'
  | 'verifier_failed';

export class ReviewGateError extends Error {
  readonly code: ReviewGateErrorCode;
  readonly details: readonly string[];

  constructor(code: ReviewGateErrorCode, message: string, details: readonly string[] = []) {
    super(message);
    this.name = 'ReviewGateError';
    this.code = code;
    this.details = [...details];
  }
}

/** README's tolerance: a final diff exceeding its estimate by more than 50% is a blown estimate. */
export const DIFF_SCOPE_TOLERANCE = 1.5;

/**
 * Where the spec-test generator is required to write, and therefore the only prefix the diff-scope
 * check counts as generated tests rather than as implementation.
 *
 * A fixed, daemon-chosen directory rather than a heuristic over filenames: "is this a test?" by
 * pattern-matching `*.test.ts` would let an implementer move its own diff out of the estimate by
 * naming a file well, which is precisely the accounting the size gate exists to prevent.
 */
export const GENERATED_TEST_PREFIX = 'test/pipenzo-generated/';

export interface CommandResult {
  readonly stdout: string;
  readonly stderr: string;
  readonly code: number;
}

/**
 * Runs one deterministic check in the ticket's worktree.
 *
 * `available` is separate from `run` on purpose: a missing `gitleaks` binary is a *skip with a
 * stated reason*, and the runner has to be able to tell that apart from a gitleaks run that
 * failed. Collapsing them would make an uninstalled scanner indistinguishable from a clean one.
 */
export interface GateCommandRunner {
  available(command: string): Promise<boolean>;
  run(command: string, args: readonly string[], cwd: string): Promise<CommandResult>;
}

export interface SpecTestGenerationResult {
  readonly sessionId: string;
  /** Repo-relative POSIX paths the generator wrote. Must sit under `GENERATED_TEST_PREFIX`. */
  readonly files: readonly string[];
}

/** The separate pass that writes the spec's tests. Never the implementer. */
export interface SpecTestGeneratorPort {
  generate(input: {
    spec: RefineSpecV1;
    worktreePath: string;
    outputPrefix: string;
  }): Promise<SpecTestGenerationResult>;
}

export interface LlmPassOutcome {
  readonly sessionId: string;
  readonly findings: readonly ReviewFindingV1[];
  /** Verifier only. A reviewer's findings are advisory and carry no verdict. */
  readonly verdict?: 'approved' | 'rejected';
  readonly vendorDiversityUnavailable?: boolean;
}

/** The seam onto agentdock's session machinery, mirroring the Refine and Implement ports. */
export interface ReviewSessionPort {
  run(request: CreateSessionV2Request): Promise<LlmPassOutcome>;
}

export interface ModelChoice {
  readonly provider: ProviderId;
  readonly model: string;
  readonly tier: ModelTier;
}

export interface ReviewGatesOptions {
  commands: GateCommandRunner;
  sessions: ReviewSessionPort;
  specTests?: SpecTestGeneratorPort;
  runGit?: PipenzoGitRunner;
  /**
   * The commands this repository builds and typechecks with. Walking skeleton: handed in rather
   * than detected, because capability detection across package managers is its own problem and
   * this ticket is about ordering.
   */
  buildCommand?: readonly string[];
  typecheckCommand?: readonly string[];
  testCommand?: readonly string[];
  /** The repository's own lint command (issue #283), same shape as the other three. Unlike
   * build/typecheck -- which every repo this runner reviews is expected to define -- not every
   * repository defines a lint script, so a missing one is reported `skipped`, not `failed`; see
   * `#runGate`'s lint branch. */
  lintCommand?: readonly string[];
}

export interface ReviewRequest {
  readonly spec: RefineSpecV1;
  readonly worktreePath: string;
  readonly baseCommit: string;
  readonly headCommit: string;
  /** The tier the implementer ran at. The verifier is checked against this and never below it. */
  readonly implementerTier: ModelTier;
  /**
   * The vendor the implementer ran on (issue #147).
   *
   * The cross-vendor rule is about the *implementer*: an adversarial verifier sharing the vendor
   * of the code it is checking shares that vendor's blind spots. Comparing the verifier against
   * the reviewer — which is what this module did before — answered a question nobody asked, since
   * the reviewer is advisory and may run anywhere.
   *
   * Optional for callers that genuinely do not know, and **fail-closed** when absent: the run is
   * recorded as `vendorDiversityUnavailable`, because a diversity claim that cannot be
   * demonstrated is exactly the kind of thing this field exists to stop the evidence block
   * implying.
   */
  readonly implementerProvider?: ProviderId;
  readonly reviewer: ModelChoice;
  readonly verifier: ModelChoice;
}

const DEFAULT_BUILD_COMMAND = ['pnpm', 'build'] as const;
const DEFAULT_TYPECHECK_COMMAND = ['pnpm', 'typecheck'] as const;
const DEFAULT_TEST_COMMAND = ['pnpm', 'test'] as const;
const DEFAULT_LINT_COMMAND = ['pnpm', 'lint'] as const;
/** pnpm's own error marker for "this script is not defined", stable across its 8/9/10 releases --
 * used to tell a repository that simply has no lint script apart from a real lint failure (issue
 * #283). Scoped to the `lint` gate only: build/typecheck are commands this runner's own repo
 * always defines, so a missing script there stays a real, reportable failure.
 *
 * Checked as a *prefix* of the combined output, not merely present anywhere in it -- verified
 * empirically that pnpm prints nothing else when a plain, non-recursive script is genuinely
 * missing (this marker line is the entire output). A caller-configured recursive `lintCommand`
 * (e.g. `pnpm -r lint`) could plausibly mix one workspace member's missing script with another's
 * real violation in the same run; requiring the marker to lead the output means that combination
 * is reported as the real failure it partly is, rather than silently downgraded to `skipped` --
 * exactly the failure shape issue #196 was about, which this whole gate exists to catch. */
const PNPM_MISSING_SCRIPT_MARKER = 'ERR_PNPM_NO_SCRIPT';
const SHA_PATTERN = /^[0-9a-f]{40}$/;
const MAX_DETAIL = 20_000;
const MAX_DIFF_CHARS = 400_000;

function truncate(value: string, limit = MAX_DETAIL): string {
  return value.length <= limit ? value : `${value.slice(0, limit)}\n[truncated]`;
}

function gateDetail(result: CommandResult): string {
  return truncate(`${result.stdout}\n${result.stderr}`.trim());
}

export class ReviewGatesRunner {
  readonly #commands: GateCommandRunner;
  readonly #sessions: ReviewSessionPort;
  readonly #specTests: SpecTestGeneratorPort | undefined;
  readonly #runGit: PipenzoGitRunner;
  readonly #build: readonly string[];
  readonly #typecheck: readonly string[];
  readonly #test: readonly string[];
  readonly #lint: readonly string[];

  constructor(options: ReviewGatesOptions) {
    this.#commands = options.commands;
    this.#sessions = options.sessions;
    this.#specTests = options.specTests;
    this.#runGit = options.runGit ?? runGitCommand;
    this.#build = options.buildCommand ?? DEFAULT_BUILD_COMMAND;
    this.#typecheck = options.typecheckCommand ?? DEFAULT_TYPECHECK_COMMAND;
    this.#test = options.testCommand ?? DEFAULT_TEST_COMMAND;
    this.#lint = options.lintCommand ?? DEFAULT_LINT_COMMAND;
  }

  /**
   * The one entry point, and a straight line. There is deliberately no public `runReviewer()` or
   * `runVerifier()`: an ordering you can only get right by calling three methods in sequence is
   * an ordering the next caller gets wrong.
   */
  async run(request: ReviewRequest): Promise<ReviewReportV1> {
    const spec = this.#validate(request);

    // Asserted here, before anything runs, rather than at the point of use. A verifier weaker than
    // the implementer is a configuration error, and the run should not burn a build and two LLM
    // passes before saying so.
    assertVerifierTierAllowed(request.implementerTier, request.verifier.tier);

    const generated = await this.#generateSpecTests(spec, request.worktreePath);
    const diff = await this.#readDiff(request);
    const scope = computeDiffScope(diff.numstat, spec);

    const deterministic = await this.#runDeterministicGates(request, generated, scope);
    const blocking = deterministic.filter(
      (gate) => gate.status === 'failed' || gate.status === 'errored',
    );

    if (blocking.length > 0) {
      // Returns. Neither LLM pass is constructed, let alone run — and the report schema refuses
      // to serialize one alongside a failed gate, so this cannot be undone downstream either.
      const onlySpecTests = blocking.every((gate) => gate.id === 'spec_tests');
      // The same carve-out as `awaiting_test_adjudication` above, for the same reason: a lone
      // `diff_scope` failure is a distinct, actionable event (issue #144) -- README's "blowing the
      // estimate by more than 50% moves the ticket to `pipenzo:awaiting-stack-approval`" -- and
      // reporting it as generic `deterministic_failed` alongside a broken build or a gitleaks hit
      // would leave nothing downstream able to tell them apart. `diff_scope` only ever fails when
      // `scope.exceededEstimate` is true (see `#runGate`), so no separate check of `scope` is
      // needed here; the gate's own status is the whole condition. If both `diff_scope` and
      // `spec_tests` are blocking together, neither carve-out applies and this falls through to
      // the generic outcome, correctly: that is a real multi-cause failure, not one this ticket's
      // single-cause distinction should paper over.
      const onlyDiffScope = blocking.every((gate) => gate.id === 'diff_scope');
      return this.#report(request, {
        outcome: onlySpecTests
          ? 'awaiting_test_adjudication'
          : onlyDiffScope
            ? 'estimate_blown'
            : 'deterministic_failed',
        deterministic,
        diffScope: scope,
      });
    }

    const reviewer = await this.#runReviewer(request, spec, diff.patch);
    const verifier = await this.#runVerifier(request, spec, diff.patch, reviewer);

    return this.#report(request, {
      outcome: verifier.verdict === 'approved' ? 'approved' : 'verifier_rejected',
      deterministic,
      diffScope: scope,
      reviewer,
      verifier,
    });
  }

  #validate(request: ReviewRequest): RefineSpecV1 {
    const parsed = refineSpecV1Schema.safeParse(request.spec);
    if (!parsed.success) {
      throw new ReviewGateError(
        'invalid_spec',
        'review requires a valid v1 refine spec to gate against',
        parsed.error.issues.slice(0, 20).map((issue) => `${issue.path.join('.') || '$'}: ${issue.message}`),
      );
    }
    if (!SHA_PATTERN.test(request.baseCommit) || !SHA_PATTERN.test(request.headCommit)) {
      throw new ReviewGateError('invalid_request', 'review requires two full commit shas');
    }
    if (!request.worktreePath.trim()) {
      throw new ReviewGateError('invalid_request', 'review requires the ticket worktree path');
    }
    return parsed.data;
  }

  async #generateSpecTests(
    spec: RefineSpecV1,
    worktreePath: string,
  ): Promise<SpecTestGenerationResult | undefined> {
    if (!this.#specTests) return undefined;
    return this.#specTests.generate({ spec, worktreePath, outputPrefix: GENERATED_TEST_PREFIX });
  }

  async #readDiff(request: ReviewRequest): Promise<{ patch: string; numstat: string }> {
    const range = `${request.baseCommit}..${request.headCommit}`;
    const numstat = await this.#runGit(
      ['diff', '--numstat', '--end-of-options', range],
      request.worktreePath,
    );
    if (numstat.code !== 0) {
      throw new ReviewGateError('diff_unavailable', 'could not read the diff for this range');
    }
    const patch = await this.#runGit(
      ['diff', '--patch', '--no-color', '--end-of-options', range],
      request.worktreePath,
    );
    if (patch.code !== 0) {
      throw new ReviewGateError('diff_unavailable', 'could not read the diff for this range');
    }
    return { patch: truncate(patch.stdout, MAX_DIFF_CHARS), numstat: numstat.stdout };
  }

  async #runDeterministicGates(
    request: ReviewRequest,
    generated: SpecTestGenerationResult | undefined,
    scope: DiffScopeV1,
  ): Promise<DeterministicGateResultV1[]> {
    const results: DeterministicGateResultV1[] = [];
    // Iterating the exported order rather than writing the calls out in sequence keeps the
    // contract and the execution in one place: reordering the gates means editing the shared
    // constant, which the report schema and the UI both read.
    for (const id of DETERMINISTIC_GATE_IDS) {
      results.push(await this.#runGate(id, request, generated, scope));
    }
    return results;
  }

  async #runGate(
    id: DeterministicGateId,
    request: ReviewRequest,
    generated: SpecTestGenerationResult | undefined,
    scope: DiffScopeV1,
  ): Promise<DeterministicGateResultV1> {
    const started = Date.now();
    const finish = (
      status: DeterministicGateResultV1['status'],
      summary: string,
      detail?: string,
    ): DeterministicGateResultV1 => ({
      id,
      status,
      summary,
      ...(detail ? { detail } : {}),
      durationMs: Math.max(0, Date.now() - started),
    });

    if (id === 'diff_scope') {
      // Pure, and the only gate that needs no subprocess. Reported against implementation files
      // only; the generated-test numbers travel alongside rather than inside (issue #145).
      //
      // The summary names the exclusion whenever there is one to name. A one-line summary reading
      // "implementation diff is 3.20x the estimate" beside a diff that is mostly generated tests
      // is the exact misreading the split exists to prevent, and the detail pane is not where a
      // reader looks before forming that impression.
      const excluded =
        scope.generatedTests.changedLines > 0
          ? ` (${scope.generatedTests.changedLines} generated-test lines excluded)`
          : '';
      return finish(
        scope.exceededEstimate ? 'failed' : 'passed',
        (scope.exceededEstimate
          ? `implementation diff is ${scope.ratio.toFixed(2)}x the ${scope.estimate.changedLines}-line estimate`
          : `implementation diff is ${scope.implementation.changedLines} lines against a ${scope.estimate.changedLines}-line estimate`) +
          excluded,
        `implementation: ${scope.implementation.changedLines} lines / ${scope.implementation.filesTouched} files\n` +
          `generated tests: ${scope.generatedTests.changedLines} lines / ${scope.generatedTests.filesTouched} files\n` +
          'the estimate is compared against the implementation half only',
      );
    }

    if (id === 'spec_tests' && !generated) {
      return finish(
        'skipped',
        'no spec-test generator is configured; the tests that would gate this diff were never written',
      );
    }

    const command =
      id === 'build'
        ? this.#build
        : id === 'typecheck'
          ? this.#typecheck
          : id === 'lint'
            ? this.#lint
            : id === 'spec_tests'
              ? this.#test
              : id === 'gitleaks'
                ? ['gitleaks', 'detect', '--source', '.', '--no-git', '--redact']
                : ['semgrep', '--error', '--quiet', '--config', 'auto', '.'];

    const executable = command[0];
    if (!executable) return finish('errored', `${id} has no command configured`);
    if (!(await this.#commands.available(executable))) {
      // Recorded as absent, never as clean. An uninstalled scanner and a scanner that found
      // nothing are different facts, and the evidence block is only worth reading if it says so.
      return finish('skipped', `${executable} is not installed; this check did not run`);
    }

    const result = await this.#commands.run(executable, command.slice(1), request.worktreePath);
    if (result.code === 0) {
      return finish('passed', `${executable} ${command.slice(1).join(' ')} succeeded`);
    }
    if (
      id === 'lint' &&
      `${result.stdout}\n${result.stderr}`.trim().startsWith(PNPM_MISSING_SCRIPT_MARKER)
    ) {
      // Not every repository defines a lint script (issue #283), unlike build/typecheck, which
      // this runner's own repo always does -- recorded as absent, the same honest way an
      // uninstalled gitleaks/semgrep binary is, never as a failure the repo did nothing to earn.
      return finish('skipped', 'no lint script is defined in this repository; this check did not run');
    }
    return finish('failed', `${executable} exited ${result.code}`, gateDetail(result));
  }

  /**
   * The reviewer: a fresh session that sees the spec and the diff.
   *
   * It is handed no session id, no worktree, and no transcript from the implementer — README is
   * explicit that same-session self-review measurably underperforms this, and the prompt builder's
   * signature is where that is enforced rather than in a convention.
   */
  async #runReviewer(
    request: ReviewRequest,
    spec: RefineSpecV1,
    diff: string,
  ): Promise<LlmReviewPassV1> {
    let outcome: LlmPassOutcome;
    try {
      outcome = await this.#sessions.run({
        provider: request.reviewer.provider,
        cwd: request.worktreePath,
        prompt: buildReviewerPrompt(spec, diff),
        model: request.reviewer.model,
      });
    } catch (error) {
      throw new ReviewGateError(
        'reviewer_failed',
        error instanceof Error ? error.message : 'the reviewer session failed',
      );
    }
    return {
      sessionId: outcome.sessionId,
      tier: request.reviewer.tier,
      model: request.reviewer.model,
      findings: [...outcome.findings],
    };
  }

  /**
   * The adversarial verifier: a separate session, at the implementer's tier or higher.
   *
   * It sees the reviewer's findings, which the reviewer never saw of the verifier — the reviewer
   * is advisory and may run below the implementer's tier, so its findings are input to be
   * adjudicated, not a second opinion of equal standing.
   */
  async #runVerifier(
    request: ReviewRequest,
    spec: RefineSpecV1,
    diff: string,
    reviewer: LlmReviewPassV1,
  ): Promise<VerifierPassV1> {
    let outcome: LlmPassOutcome;
    try {
      outcome = await this.#sessions.run({
        provider: request.verifier.provider,
        cwd: request.worktreePath,
        prompt: buildVerifierPrompt(spec, diff, reviewer.findings),
        model: request.verifier.model,
      });
    } catch (error) {
      throw new ReviewGateError(
        'verifier_failed',
        error instanceof Error ? error.message : 'the verifier session failed',
      );
    }
    if (outcome.verdict !== 'approved' && outcome.verdict !== 'rejected') {
      throw new ReviewGateError('verifier_failed', 'the verifier returned no verdict');
    }
    return {
      sessionId: outcome.sessionId,
      tier: request.verifier.tier,
      model: request.verifier.model,
      findings: [...outcome.findings],
      verdict: outcome.verdict,
      // README: on a single-vendor install the cross-vendor tiebreak has nothing to pick from. It
      // degrades to same-vendor and *records* that it did — a verifier that could not be
      // cross-vendor is a weaker check, and the evidence block must not imply otherwise.
      //
      // Compared against the implementer, and fail-closed when the implementer's vendor is not
      // known: `true` says "this run cannot show it was cross-vendor", which is the honest thing
      // to record. `false` would be a claim, and this module does not get to make one it cannot
      // support.
      vendorDiversityUnavailable:
        outcome.vendorDiversityUnavailable ??
        (request.implementerProvider === undefined ||
          request.verifier.provider === request.implementerProvider),
    };
  }

  #report(
    request: ReviewRequest,
    parts: {
      outcome: ReviewReportV1['outcome'];
      deterministic: DeterministicGateResultV1[];
      diffScope: DiffScopeV1;
      reviewer?: LlmReviewPassV1;
      verifier?: VerifierPassV1;
    },
  ): ReviewReportV1 {
    // Parsed, not cast. The schema's own ordering invariant is the last line of defence, so it
    // runs on every report this module produces rather than only on ones that cross the wire.
    return reviewReportV1Schema.parse({
      schemaVersion: 1,
      outcome: parts.outcome,
      baseCommit: request.baseCommit,
      headCommit: request.headCommit,
      implementerTier: request.implementerTier,
      deterministic: parts.deterministic,
      diffScope: parts.diffScope,
      ...(parts.reviewer ? { reviewer: parts.reviewer } : {}),
      ...(parts.verifier ? { verifier: parts.verifier } : {}),
    });
  }
}

/**
 * README's hard rule, as a function: the adversarial verifier is never a weaker model tier than
 * the implementer it is checking. Not a preference, not a default — a throw.
 *
 * The reviewer is deliberately exempt and is not checked here. It is advisory: its findings feed
 * the implement retry and are adjudicated by a same-or-higher-tier verifier, so the cross-tier
 * regression evidence (3 fixes against 13 new bugs) does not apply to it.
 */
export function assertVerifierTierAllowed(implementer: ModelTier, verifier: ModelTier): void {
  if (modelTierRank(verifier) < modelTierRank(implementer)) {
    throw new ReviewGateError(
      'verifier_tier_too_low',
      `a ${verifier}-tier verifier cannot gate a ${implementer}-tier implementer`,
      [`implementer=${implementer}`, `verifier=${verifier}`],
    );
  }
}

/**
 * The same-or-higher rule as **executable policy** rather than as an assertion somebody remembers
 * to call, plus the cross-vendor tiebreak (Pipenzo issue #147).
 *
 * `assertVerifierTierAllowed` answers "may this verifier gate this implementer?". This answers the
 * question that actually comes up: "given what is installed, which verifier should gate it?" —
 * and it is the difference between a rule and a policy. A rule you check after choosing is a rule
 * you can satisfy by choosing badly and then not checking.
 *
 * ## The ordering, and why tier ascends
 *
 * 1. **Floor.** Candidates below the implementer's tier are eliminated. Not deprioritised.
 * 2. **Lowest qualifying tier wins.** README states the rule as a floor — "never below" — and a
 *    floor is not a target. Sending a frontier verifier at a cheap-tier ticket costs real money
 *    for a check the rule already considers sufficient, and Pipenzo's whole per-ticket budget
 *    framing is about not spending that quietly.
 * 3. **Cross-vendor tiebreak among equal tiers.** Two candidates at the winning tier: the one from
 *    a different vendor than the implementer wins. A verifier sharing the implementer's vendor
 *    shares its blind spots, and an adversarial check that fails the same way as the thing it is
 *    checking is not adversarial.
 * 4. **Deterministic beyond that.** Ties are broken by provider then model name, so the same
 *    installed set always selects the same verifier — a gate that picks a different model each run
 *    produces evidence nobody can compare across runs.
 *
 * When no candidate clears the floor, this returns `none_eligible` rather than the best available.
 * There is no "closest match" here on purpose: silently downgrading is the failure mode the rule
 * exists to prevent, and it is worse than not running.
 */
export type VerifierSelection =
  | {
      readonly outcome: 'selected';
      readonly verifier: ModelChoice;
      /** True when the selected verifier is a different vendor from the implementer. */
      readonly crossVendor: boolean;
      /**
       * True when no eligible cross-vendor candidate existed at all — a single-vendor install.
       * README requires this be *recorded on the run*: a verifier that could not be cross-vendor
       * is a weaker check, and the evidence block must not imply otherwise.
       */
      readonly vendorDiversityUnavailable: boolean;
    }
  | { readonly outcome: 'none_eligible'; readonly reason: string };

export function selectVerifier(input: {
  implementer: ModelChoice;
  candidates: readonly ModelChoice[];
}): VerifierSelection {
  const floor = modelTierRank(input.implementer.tier);
  const eligible = input.candidates.filter(
    (candidate) => modelTierRank(candidate.tier) >= floor,
  );
  if (eligible.length === 0) {
    return {
      outcome: 'none_eligible',
      reason: `no installed model is at or above the implementer's ${input.implementer.tier} tier`,
    };
  }
  const lowestQualifyingRank = Math.min(
    ...eligible.map((candidate) => modelTierRank(candidate.tier)),
  );
  const atTier = eligible.filter(
    (candidate) => modelTierRank(candidate.tier) === lowestQualifyingRank,
  );
  const sorted = [...atTier].sort(
    (a, b) => a.provider.localeCompare(b.provider) || a.model.localeCompare(b.model),
  );
  const crossVendor = sorted.filter(
    (candidate) => candidate.provider !== input.implementer.provider,
  );
  // The tiebreak is scoped to the winning tier, not to the whole eligible set: reaching up a tier
  // to find a different vendor would break the floor-is-not-a-target rule above, and the tier
  // relationship is the one README backs with regression evidence.
  const verifier = crossVendor[0] ?? sorted[0];
  if (!verifier) {
    return { outcome: 'none_eligible', reason: 'no verifier candidate could be selected' };
  }
  return {
    outcome: 'selected',
    verifier,
    crossVendor: verifier.provider !== input.implementer.provider,
    vendorDiversityUnavailable: !eligible.some(
      (candidate) => candidate.provider !== input.implementer.provider,
    ),
  };
}

/** Repo-relative POSIX paths under the generated-test prefix are tests; everything else is not. */
export function isGeneratedTestPath(path: string): boolean {
  return path.replaceAll('\\', '/').startsWith(GENERATED_TEST_PREFIX);
}

/**
 * Splits `git diff --numstat` output into implementation and generated-test totals and compares
 * the implementation half against the Refine estimate (issue #145's logic, folded in here because
 * the diff-scope gate cannot be written without it).
 *
 * Binary files report `-` for both counts in numstat; they contribute a touched file and no lines,
 * which is the honest reading — a changed binary is a real change with no line count to give.
 */
export function computeDiffScope(numstat: string, spec: RefineSpecV1): DiffScopeV1 {
  const implementation = { changedLines: 0, filesTouched: 0 };
  const generatedTests = { changedLines: 0, filesTouched: 0 };

  for (const line of numstat.split(/\r?\n/)) {
    if (!line.trim()) continue;
    const parts = line.split('\t');
    if (parts.length < 3) continue;
    const [added, deleted, rawPath] = parts;
    const path = rawPath ?? '';
    if (!path) continue;
    const lines =
      added === '-' || deleted === '-' ? 0 : (Number(added) || 0) + (Number(deleted) || 0);
    const bucket = isGeneratedTestPath(path) ? generatedTests : implementation;
    bucket.changedLines += lines;
    bucket.filesTouched += 1;
  }

  const estimate = {
    changedLines: spec.estimate.changedLines,
    filesTouched: spec.estimate.filesTouched,
  };
  // A zero estimate has no meaningful ratio; treat any real diff against it as a blown estimate
  // rather than dividing by zero into Infinity.
  const ratio =
    estimate.changedLines > 0
      ? implementation.changedLines / estimate.changedLines
      : implementation.changedLines > 0
        ? Number.POSITIVE_INFINITY
        : 0;

  return {
    implementation,
    generatedTests,
    estimate,
    exceededEstimate: ratio > DIFF_SCOPE_TOLERANCE,
    ratio: Number.isFinite(ratio) ? Number(ratio.toFixed(4)) : Number.MAX_SAFE_INTEGER,
  };
}

function renderCriteria(spec: RefineSpecV1): string[] {
  return spec.acceptanceCriteria.map((criterion) => `  ${criterion.id}: ${criterion.text}`);
}

/**
 * Builds the reviewer's prompt from the spec and the diff.
 *
 * Two parameters, and neither is a transcript. That is the separation property expressed where it
 * cannot be forgotten: there is no argument through which the implementer's session could reach
 * this pass.
 */
export function buildReviewerPrompt(spec: RefineSpecV1, diff: string): string {
  return [
    'You are reviewing a diff against the spec it was written to satisfy. You did not write this',
    'code and you are not seeing the session that did — judge the diff on its own terms.',
    '',
    'Your findings are advisory. A separate verifier decides whether this ships, so report what',
    'you actually see rather than calibrating to a verdict.',
    '',
    `Ticket: ${spec.issue.repo}#${spec.issue.number} — ${spec.issue.title}`,
    '',
    'Acceptance criteria',
    ...renderCriteria(spec),
    '',
    'Explicitly out of scope — flag anything in the diff that goes beyond these bounds',
    ...spec.outOfScope.map((entry) => `  - ${entry}`),
    '',
    'Diff',
    diff,
  ].join('\n');
}

/** The verifier's prompt: the spec, the diff, and the reviewer's advisory findings to adjudicate. */
export function buildVerifierPrompt(
  spec: RefineSpecV1,
  diff: string,
  reviewerFindings: readonly ReviewFindingV1[],
): string {
  const findings = reviewerFindings.map(
    (finding) =>
      `  [${finding.severity}] ${finding.path ?? 'general'}${finding.line ? `:${finding.line}` : ''} — ${finding.message}`,
  );
  return [
    'You are the adversarial verifier. You are the gate: your verdict decides whether this diff is',
    'offered to a human for publishing. Assume the diff is wrong until it demonstrates otherwise.',
    '',
    'An advisory reviewer has already looked at this. Its findings are input for you to adjudicate,',
    'not conclusions — it may run at a lower model tier than the code it read, so confirm anything',
    'you act on against the diff itself.',
    '',
    `Ticket: ${spec.issue.repo}#${spec.issue.number} — ${spec.issue.title}`,
    '',
    'Acceptance criteria — every one of these must hold',
    ...renderCriteria(spec),
    '',
    'Explicitly out of scope',
    ...spec.outOfScope.map((entry) => `  - ${entry}`),
    ...(findings.length > 0 ? ['', 'Reviewer findings to adjudicate', ...findings] : []),
    '',
    'Diff',
    diff,
  ].join('\n');
}
